import 'package:hive/hive.dart';
import 'package:news_c13_friday/model/sources_response.dart';

part 'news_response.g.dart'; // This file is generated by running `flutter packages pub run build_runner build`

@HiveType(typeId: 2)
class NewsResponse extends HiveObject {
  @HiveField(0)
  String? status;

  @HiveField(1)
  String? code;

  @HiveField(2)
  String? message;

  @HiveField(3)
  int? totalResults;

  @HiveField(4)
  List<Articles>? articles;

  NewsResponse({
    this.status,
    this.code,
    this.message,
    this.totalResults,
    this.articles,
  });

  NewsResponse.fromJson(Map<String, dynamic> json) {
    status = json['status'];
    code = json['code'];
    message = json['message'];
    totalResults = json['totalResults'];
    if (json['articles'] != null) {
      articles = <Articles>[];
      json['articles'].forEach((v) {
        articles!.add(Articles.fromJson(v));
      });
    }
  }
}

@HiveType(typeId: 3)
class Articles extends HiveObject {
  @HiveField(0)
  Sources? source;

  @HiveField(1)
  String? author;

  @HiveField(2)
  String? title;

  @HiveField(3)
  String? description;

  @HiveField(4)
  String? url;

  @HiveField(5)
  String? urlToImage;

  @HiveField(6)
  String? publishedAt;

  @HiveField(7)
  String? content;

  Articles({
    this.source,
    this.author,
    this.title,
    this.description,
    this.url,
    this.urlToImage,
    this.publishedAt,
    this.content,
  });

  Articles.fromJson(Map<String, dynamic> json) {
    source = json['source'] != null ? Sources.fromJson(json['source']) : null;
    author = json['author'];
    title = json['title'];
    description = json['description'];
    url = json['url'];
    urlToImage = json['urlToImage'];
    publishedAt = json['publishedAt'];
    content = json['content'];
  }
}
