import 'package:hive/hive.dart';

part 'sources_response.g.dart'; // This file is generated by running `flutter packages pub run build_runner build`

@HiveType(typeId: 0)
class SourcesResponse extends HiveObject {
  @HiveField(0)
  String? status;

  @HiveField(1)
  String? code;

  @HiveField(2)
  String? message;

  @HiveField(3)
  List<Sources>? sources;

  SourcesResponse({
    this.status,
    this.sources,
    this.code,
    this.message,
  });

  SourcesResponse.fromJson(Map<String, dynamic> json) {
    status = json['status'];
    code = json['code'];
    message = json['message'];
    if (json['sources'] != null) {
      sources = <Sources>[];
      json['sources'].forEach((v) {
        sources!.add(Sources.fromJson(v));
      });
    }
  }
}

@HiveType(typeId: 1)
class Sources extends HiveObject {
  @HiveField(0)
  String? id;

  @HiveField(1)
  String? name;

  @HiveField(2)
  String? description;

  @HiveField(3)
  String? url;

  @HiveField(4)
  String? category;

  @HiveField(5)
  String? language;

  @HiveField(6)
  String? country;

  Sources({
    this.id,
    this.name,
    this.description,
    this.url,
    this.category,
    this.language,
    this.country,
  });

  Sources.fromJson(Map<String, dynamic> json) {
    id = json['id'];
    name = json['name'];
    description = json['description'];
    url = json['url'];
    category = json['category'];
    language = json['language'];
    country = json['country'];
  }
}
